### PR TITLE
Elbow Removal Service

### PR DESCRIPTION
**Pull request by ElbowRemovalService**
Contains the mods HarderBetterFasterScooter (v0.9.8) and No Game Scaling (v1.1).

### CODE REVIEW

**Comment by apocalyptech** [comment]
Hello -- Have you gotten permission from the other mod authors to redistribute their mods in a modpack?  If so, could you provide it in this PR?  Thanks!

-CJ

**Comment by ElbowRemovalService** [comment]
I have tried to reach out to as many authors as possible, but I could have
missed a few, especially in the process of removing and adding files.
I can re-ask as many as possible, if you would like.
I must also confess that I am not aware as to what a "PR" is.

**Comment by apocalyptech** [comment]
Hey, sorry this has been sitting out here for so long, btw -- I sort of legit just forgot about it.  I'll take another look at this over the weekend and see if we can get it merged in.  Just like to be careful w/ modpack type stuff 'cause we've had problems with that in the past.  I'll give you a buzz if I've got any questions, etc!

**Comment by LollosaurusRex** [comment]
Hi I noticed it's been a few months more, @ElbowRemovalService I figured we could remind you of this. Apoc as well.

**Comment by apocalyptech** [comment]
Eh, so this one's easy for me to lose track of since the tasklist essentially involves so much manual verification.

The main reason it didn't get merged right away is just that we've gotten burned with modpacks in the past -- sometimes folks don't want their stuff redistributed, and unfortunately a lot of folks never specified any terms or whatever when releasing their mods, so we generally feel like we've gotta be careful about it.

I know you'd said you'd reached out to everyone feasible whose mods were included in here, and I apologize that it's now taken like 10 months to explicitly ask for it, but if you'd provide a list of folks whose mods are included in here, along with the state of their approval for having stuff redistributed (even if it's just "I have no idea how to get ahold of this person"), that may kick things along.  I really should've just asked for something like that right away, so apologies for this hideous delay (especially since it's probably well off your own radar by this point too).

If anything there's from my mod, of course, you're welcome to use it however you like (all my stuff is explicitly in the public domain for BL2/TPS).  :)

Anyway, cheers -- I *would* like to get this merged in someday.

**Pull request closed without merging**
