### PR TITLE
Create New BL2 Mod: Shield Behavior Overhaul by Orudeon - French v1.0.0

### PR DESCRIPTION
**Pull request by Astor63**
... Update Main ReadMe by adding *Orudeon's Shield Behavior Overhaul - French* on it

### CODE REVIEW

**Comment by apocalyptech** [comment]
Ohhhhhhh, bother.

Sorry, we'd totally misinterpreted the stuff you posted without looking too closely into it.  What you were doing is great, please keep doing so!  No need to ask permission or whatever for what was going on there.  :)  I'll re-invite you back in.

Sorry again for the false alarm!

-CJ

**Comment by Astor63** [comment]
Hello there

Well, the reason why I previously don’t ask any authorization to the original mod authors (Orudeon, Aaron0000, etc…), it’s simply because I don’t use/modify their mod in anyway, but just translate the new/additional English line(s) of code ```Description``` in French, __without uploading the mod himself__.

Honestly, as all the Mods are in a directory named *French Translation*, for me, it was self-evident that the content was obvious: a *French language patch*!

In fact, I had the idea to realize (and publish) these French translations for two reasons:
- All Francophones do not understand English, so it can be very useful for them... and it is for this reason that the ReadMe is written in French :smirk: 
- For those who master English, but prefer to play BL2 or TPS in French because the French dubbing is really well done, having lines of text in English "here and there" in a game in French, gives the impression of playing with a broken, or at least unfinished game :unamused: 

Astor

Note: By the way, *UCP 2.2 Patch* for TPS is already done since one week, and I am currently occupied with the French translation from *UCP 4.1 Patch* for BL2… but it will still take me a moment because it's quite a big piece (especially the "skill" part) to translate; and with the Christmas holidays approaching, I will not have much free time to work on it.

**Comment by apocalyptech** [comment]
Yeah, we'd misunderstood at first and then figured it out afterwards.  Sorry to even bring it up!  What you're doing is totally fine, and appreciated!

:)

Very nice at the TPS patch, I hadn't known that was coming out!

**Comment by apocalyptech** [comment]
Oh, by the way - since you're in the BLCM group now, you don't acutally *have* to use Pull Requests anymore if you don't want to.  You're able to commit directly to the main repo now.  :)

**Comment by Astor63** [comment]
Well, thanks for the info, but is not that __*if I don't want to*__, but more __*because I have to*__ :confused:

__Short explanation:__

I use __*GitHub Desktop*__, and curiously, that's doesn't work with BLCM when I hit the __*Fetch Origin*__ button.

I mean, that's work fine with my (others) following repertories:

- [__Astor63/BL2-Mods__](https://github.com/Astor63/BL2-Mods)
- [__Astor63/TPS-Mods__](https://github.com/Astor63/TPS-Mods)
- [__Astor63/DirectImput-Generic-Controller-Fix__](https://github.com/Astor63/DirectImput-Generic-Controller-Fix)

... I just hit __*commit to master*__ button, following by the __*Fetch Origin*__ button on __*GitHub Desktop*__, and that's it, the commit is done.

But with BLCM, after hitting the __*Fetch Origin*__ button on *GitHub Desktop*, I must open [__Astor63/BLCMods__](https://github.com/Astor63/BLCMods?organization=Astor63&organization=Astor63) or [__BLCM/BLCMods__](https://github.com/BLCM/BLCMods/commits/master) in a browser (in the 2 cases I must be logged on Github) and hit the __*Pull request*__ link.

Once a pull request is open on BLCM, the __*Fetch Origin*__ button on __*GitHub Desktop*__ work well and I can add many files as I need directly from __*GitHub Desktop*__... and to finish, on the browser, I hit the __*commit*__ button, following by __*comfirm commit*__ button on my browser to end the operation.

... but perhaps I do it in a wrong way?

Of course, if anybody has good advices to avoid all theses (useless) steps on BLCM, I'll take them... all of them :wink:

Astor

**Comment by apocalyptech** [comment]
Heh, yeah, that seems cumbersome.  I've actually never used Github Desktop so I'm not sure how it works exactly...  When you add a project to Github Desktop, do you have to give it the URL to the project?  If so, you might want to try re-adding the main BLCM repo.  Before you were added to the BLCM group, the clone URL would have been:

https://github.com/BLCM/BLCMods.git

But now that you're in the BLCM group, it will have changed to:

git@github.com:BLCM/BLCMods.git

If Github Desktop was still using the first one, that could maybe be why it's not working.  (Because only the new one actually supports writing to the repo.)

**Comment by Astor63** [comment]
Ah! That's a hint.

The __*Primary Remote Repository*__ setting from BLCM on my *GitHub Desktop* actually is https://github.com/Astor63/BLCMods.git because it's (still) the forked version of BLCM.

I will clone the main BLCM repository again to get the https://github.com/BLCM/BLCMods.git as __*Primary Remote Repository*__, and use a *dummy* ReadMe to make a test.

If that don't work, I will change the __*Primary Remote Repository*__ to git@github.com:BLCM/BLCMods.git.

... so don't worry if you see a lot of update from the same *dummy* ReadMe in Astor folder in BLCM.

**Comment by Astor63** [comment]
Work on the first try with a new clone from the main BLCM repository and the https://github.com/BLCM/BLCMods.git as __*Primary Remote Repository*__.

Now on my Github Desktop, I just hit __*commit to master*__ button to create my commits, following by the __*Fetch Origin*__ button to upload them, and it's done: I have a pristine *GitHub Desktop Dummy* folder in my BL2 Mods :wink:

For sure, my live will be more easy... thanks for the hint CJ, I really appreciate

**Pull request merged**
