### PR TITLE
Delete ALL the ReadMe

### PR DESCRIPTION
**Pull request by Astor63**
I don't have any conflict with the identical files [here](https://github.com/Astor63/BL2-Mods)

so I try to find a solution to the ReadMe conflict on BLCM...

### CODE REVIEW

**Comment by apocalyptech** [comment]
Howdy, so there's some weird conflicts in this one, and I just wanted to make sure that I was resolving them properly...  Were you hoping to have these following files deleted?

```        deleted by them: Borderlands 2 mods/Astor/Double Quest Reward Redux/ReadMe.md
        deleted by them: Borderlands 2 mods/Astor/Dr Zed E-Tech Geek/ReadMe.md
        deleted by them: Borderlands 2 mods/Astor/Hammerlock Jakobs Sponsor/ReadMe.md
        deleted by them: Borderlands 2 mods/Astor/SMG Dahl Discord Solver/SMG Dahl Discord Solver - Moxxi Edition v1.1.1/ReadMe.md
        deleted by them: Borderlands 2 mods/Astor/readme.md
```

**Comment by Astor63** [comment]
Well... few days ago, when I update SMG Dahl Discord Solver - Moxxi Edition v1.1.1 to v1.1.2, I have a conflict with 1 non-existant ReadMe (Borderlands 2 mods/Astor/SMG Dahl Discord Solver/SMG Dahl Discord Solver - Moxxi Edition v1.1.1/ReadMe.md)... and now the same conflict apply to 4 ReadMe. 🥇 

I don't understand what is wrong with them, because they are exactely identical to those from this repertory: https://github.com/Astor63/BL2-Mods, and I never have any problem with them on this repertory.

I don't have any idea how to resolve the conflict with non-existant ReadMe, so I try to delete them all, to upload new one... that's the reason why I hope have these files deleted.

Sorry for all the troubles  :disappointed:

Astor 

Note to @apocalyptech: Apparently you deleted 4 of 5 ReadMe conflicting files -thanks for that!-, but the confict with Borderlands 2 mods/Astor/Double Quest Reward Redux/ReadMe.md is still there, so the commit cannot be done.

**Comment by apocalyptech** [comment]
Hah, no trouble; Github can be weird, and I'm pretty sure that these problems are just because past merges were done a bit differently.  I'll take a peek again once I'm back home

**Comment by Astor63** [comment]
It's what I think too... I mean that the problem is "just" because past merges... because when I make a new commit, Github seems to repeating some old commits already done 1 week ago.

So in the case of "Borderlands 2 mods/Astor/SMG Dahl Discord Solver/SMG Dahl Discord Solver - Moxxi Edition v1.1.1/ReadMe.md", if I have updated the repertory to v1.1.2, the update for the "old" ReadMe file cannot work, because the previous directory (v1.1.1) don't exist anymore.

To avoid the repetition of this kind of stupid problem, I don't update the repertory anymore (eg: v1.1.1 to v1.1.2), and just give it his name (SMG Dahl Discord Solver - Moxxi Edition)... but I cannot solve the previous conflicts for non-existant ReadMe in non-existant repertory

**Comment by apocalyptech** [comment]
Okay, I think this should be good to go now, and should *hopefully* not have the same problem in the future.  You may want to make sure that `SMG Dahl Discord Solver - Moxxi Edition v1.1.2.blcm` is still good to go, and the version that you expect it to be.  :)

**Comment by Astor63** [comment]
Thank you, I'll check... and upload the (new) ReadMe files.

Anyway, if anything go wrong with any BLCM file, the repertory https://github.com/Astor63/BL2-Mods, where the original BLCM files are stored, can be used as a backup... as the saying goes: "Never underestimate the usefulness of having a backup copy"  :wink:

**Pull request merged**
